from __future__ import annotations

from typing import Any, Dict, Protocol


class LayerGatewayProtocol(Protocol):
    """Single injection surface every layer must expose to Operations Runtime."""

    def describe(self) -> Dict[str, Any]: ...
    def healthcheck(self) -> Dict[str, Any]: ...
    def validate_contract(self) -> Dict[str, Any]: ...
    def execute(self, command: Any) -> Dict[str, Any]: ...
